[versions]
# main
kotlin = "1.8.0"
korge = "4.0.0-alpha-6"
# test
mockito-kotlin = "4.1.0"
mockito-inline = "4.11.0"

[libraries]
# main
korge = { module = "com.soywiz.korlibs.korge2:korge-jvm", version.ref = "korge" }
# test
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito-inline" }
